name: CI

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  standard:
    name: Lint with Standard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run standardrb
        uses: standardrb/standard-ruby-action@f533e61f461ccb766b2d9c235abf59be02aea793
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      checks: write
      contents: read

  build:
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    continue-on-error: ${{ matrix.continue-on-error }}

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3"]
        rails: ["7.1", "7.2"]
        continue-on-error: [false]
        include:
          - ruby: "head"
            rails: "7.2"
            continue-on-error: true
          - ruby: "3.3"
            rails: "main"
            continue-on-error: true
          - ruby: "head"
            rails: "main"
            continue-on-error: true

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_VERSION: ${{ matrix.rails }}
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Generate lockfile
        run: bundle lock

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('Gemfile.lock') }}

      - name: Set up Scenic
        run: bin/setup

      - name: Run fast tests
        run: bundle exec rake spec
        continue-on-error: ${{ matrix.continue-on-error }}

      - name: Run acceptance tests
        run: bundle exec rake spec:acceptance
        continue-on-error: ${{ matrix.continue-on-error }}
